language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
install:
   - composer install
before_script:
- composer install -n --dev --prefer-source
script:
   - vendor/bin/phpunit vendor/academe/sagepay
